export const ActionTypes = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  FETCH_TASKS: "FETCH_TASKS",
  UPDATE_TASK: "UPDATE_TASK",
  ADD_TASK: "ADD_TASK",
  SNACKBAR_OPEN: "SNACKBAR_OPEN",
  SNACKBAR_CLOSE: "SNACKBAR_CLOSE",
};
